@base_url = http://localhost:4004
@admin_path = /input-admin

####
## Get the Metadata
GET {{base_url}}{{admin_path}}/$metadata HTTP/1.1

#######
## Insert the Calibration Values
POST {{base_url}}{{admin_path}}/InsertCalibrationValues() HTTP/1.1
Content-Type: application/json