@base_url = http://localhost:4004
#@advent_of_code_path = /odata/v4/advent-of-code2023
@advent_of_code_path = /odata/v4/advent-of-code2023

####
## Get the Metadata
GET {{base_url}}{{advent_of_code_path}}/$metadata HTTP/1.1

#######
## Get the Sum of Calibration Values
GET {{base_url}}{{advent_of_code_path}}/SumCalibrationValues() HTTP/1.1


#### Day 2
@day2_path = /odata/v4/cube-conundrum
#######
## Get the number of valid games
# 2317 Yeah
GET {{base_url}}{{day2_path}}/GetNumberOfValidGames(r=12,g=13,b=14) HTTP/1.1

#######
## Get the Power of Sets
GET {{base_url}}{{day2_path}}/GetPowerOfSets() HTTP/1.1


#### Day 3
#@day3_path = /odata/v4/engine-schematic
@day3_path = /engine-schematic
#######
## Get Engine Schematics
GET {{base_url}}{{day3_path}}/EngineSchematic HTTP/1.1

#######
## Get Sum of Part Numbers
GET {{base_url}}{{day3_path}}/GetSumOfPartNumbers() HTTP/1.1
