@base_url = http://localhost:4004
@advent_of_code_path = /odata/v4/advent-of-code2023

####
## Get the Metadata
GET {{base_url}}{{advent_of_code_path}}/$metadata HTTP/1.1

#######
## Get the Sum of Calibration Values
GET {{base_url}}{{advent_of_code_path}}/SumCalibrationValues() HTTP/1.1
