@base_url = http://localhost:4004
@advent_of_code_path = /odata/v4/advent-of-code2023

####
## Get the Metadata
GET {{base_url}}{{advent_of_code_path}}/$metadata HTTP/1.1

#######
## Get the Sum of Calibration Values
GET {{base_url}}{{advent_of_code_path}}/SumCalibrationValues() HTTP/1.1


#### Day 2
@day2_path = /odata/v4/cube-conundrum
#######
## Get the number of valid games
# 3968 Too High
# 3891 Too High
# 325
# 2317 Yeah
GET {{base_url}}{{day2_path}}/GetNumberOfValidGames(r=12,g=13,b=14) HTTP/1.1
